version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env

  backend:
    image: kotpilota/kittygram_backend:latest
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app/collected_static/
      - media:/app/media/

  frontend:
    image: kotpilota/kittygram_frontend:latest
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
    depends_on:
      - backend

  gateway:
    image: kotpilota/kittygram_gateway:latest
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
      - frontend