version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env
    restart: always

  backend:
    image: kotpilota/kittygram_backend:latest
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media
    restart: always

  frontend:
    image: kotpilota/kittygram_frontend:latest
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - backend
    restart: always

  gateway:
    image: kotpilota/kittygram_gateway:latest
    env_file: .env
    ports:
      - 8082:80
    volumes:
      - static:/staticfiles
      - media:/media
    depends_on:
      - backend
      - frontend
    restart: always